### ISSUE TITLE
Reorganize the development of the new design

### ISSUE THREAD

**Issue by openp2pdesign** [fablabbcn/fablabs.io#111]
A new visual design and frontend have been under development, but for the moment it has stopped at the [end of July](https://github.com/fablabbcn/fablabsio-design/commit/f37fa813637d98497666e6a5f6b5c04790ed865e) or [beginning of August](https://github.com/fablabbcn/fablabs-ui/commit/f310c118b29623dea77ac311be5ee8af8bba8e10) 2016.

I will reorganize this process, including its two current repositories:
- Frontend: [https://github.com/fablabbcn/fablabs-ui](https://github.com/fablabbcn/fablabs-ui)
- UX/Design: [https://github.com/fablabbcn/fablabsio-design](https://github.com/fablabbcn/fablabsio-design)

There will be an update about this soon.

**Comment by jsphpl** [comment]
What's the status with the new design? Why has it stalled? How can we help make it happen?

**Comment by viktorsmari** [comment]
There is actually work going on **right now**, but on a different repo: https://github.com/fbaiodias/fablabs.io/commits/redesign

**Comment by jsphpl** [comment]
Great! So it wouldn't make sense to contribute fixes concerning design on this repo here?

**Comment by openp2pdesign** [comment]
> What's the status with the new design? 

There's a new redesigned interface done in Sketch, now it is converted to the front-end here:
https://github.com/fbaiodias/fablabs.io/tree/redesign

> Why has it stalled?

Mainly because we were too busy in

1. Getting funding
1. Managing changes in the team
1. Improving the infrastructure and APIs

> How can we help make it happen?

Check with @LinusEkenstam and @fbaiodias how to improve the work on https://github.com/fbaiodias/fablabs.io/tree/redesign

**Comment by openp2pdesign** [comment]
> Great! So it wouldn't make sense to contribute fixes concerning design on this repo here?

Right now the best thing is to contribute to https://github.com/fbaiodias/fablabs.io/tree/redesign

@LinusEkenstam @fbaiodias: we should set up issues regarding the front-end development in your current work, to make it easier to other developer to help you

**Comment by openp2pdesign** [comment]
Furthermore: we are not using these two repositories any longer:

- Frontend: [https://github.com/fablabbcn/fablabs-ui](https://github.com/fablabbcn/fablabs-ui)
- UX/Design: [https://github.com/fablabbcn/fablabsio-design](https://github.com/fablabbcn/fablabsio-design)

**Comment by viktorsmari** [comment]
@openp2pdesign Can we archive those repos then? Or indicate that they are deprecated in the README and top description?

**Comment by openp2pdesign** [comment]
@viktorsmari done! I've just added the info that they are deprecated

**Comment by jsphpl** [comment]
Thanks everybody for the update!

> Furthermore: we are not using these two repositories any longer

> There's a new redesigned interface done in Sketch

Are the design files available somewhere so we can help implement?

The new design is going to be implemented on the code base of the current platform as server-rendered by rails, right? The fablabs-ui repo suggested a rewrite in ember, but i suppose that's deprecated, correct?

**Comment by openp2pdesign** [comment]
Thanks everybody for the 

> update!

Thank you for the help! :-)

> Are the design files available somewhere so we can help implement?

We are reorganizing them right now so that we can share them! I'll post soon here something

> The new design is going to be implemented on the code base of the current platform as server-rendered by rails, right? The fablabs-ui repo suggested a rewrite in ember, but i suppose that's deprecated, correct?

Yes, Rails views in HAML and Bootstrap, no Ember or other things.

**Comment by openp2pdesign** [comment]
> Are the design files available somewhere so we can help implement?

Here's the sketch file: 
https://drive.google.com/open?id=1BkCO5Ie1YJCd-O9oArGJEydnIMlxi6Lp

**Comment by openp2pdesign** [comment]
For the next 2-3 weeks, let's move this discussion to this specific issue https://github.com/fablabbcn/fablabs.io/issues/406
