### ISSUE TITLE
Navbar consistent across all subdomains

### ISSUE THREAD

**Issue by openp2pdesign** [fablabbcn/fablabs.io#143]
Navbar should be consistent across all subdomains, which probably will use different backends, but should always use the same Boostrap-based style for consistency.

See for example the current fablabs.io:
![screen shot 2016-11-26 at 20 03 34](https://cloud.githubusercontent.com/assets/1458229/20642626/e6213e82-b413-11e6-897c-60ffc6130dc0.png)

and the current discuss.fablabs.io:
![screen shot 2016-11-26 at 20 03 43](https://cloud.githubusercontent.com/assets/1458229/20642627/e7e0a7d0-b413-11e6-88bd-35173b2678d8.png)

They are similar but clearly not the same. Ideally users should not experience a difference between the subdomains.

**Comment by openp2pdesign** [comment]
... and footer as well, whenever possible

**Comment by viktorsmari** [comment]
Right now, different subdomains are completely different websites with different purposes.
The **forum** is one thing, **network** is another, and **projects** is another.
