### ISSUE TITLE
General statistics API

### ISSUE THREAD

**Issue by openp2pdesign** [fablabbcn/fablabs.io#162]
We can already get some general stats from the current API, but this could be improved in order to have an updated dataviz to show the size and evolution of the platform (also related to MAKE-IT).

A first example would be stats regarding `Users`, anonymized and even only with the _created_at_ field, in order to show the growth of the platform: 

`{"user_stats":
[
  {"random_id":1,"created_at":"5/12/2016"},
  {"random_id":2,"created_at":"5/12/2016"}
  ]
}`

Also the `Labs` API do not show the _created_at_ field, so this could be added or added to a generic Stats API together with `Users` and other stats.

**Comment by openp2pdesign** [comment]
We need a _created_at_ field also for `Labs`, at least in the current APIs

**Comment by viktorsmari** [comment]
Partially implemented under https://fablabs.io/metrics

We can improve in the future
