### ISSUE TITLE
Bug in the labs list when adding a new lab

### ISSUE THREAD

**Issue by openp2pdesign** [fablabbcn/fablabs.io#178]
When adding a new lab, in the labs list there are some strange items (more than one!):

![screen shot 2016-12-14 at 15 34 28](https://cloud.githubusercontent.com/assets/1458229/21192825/220dd382-c22a-11e6-936e-0d3767a21d77.png)

**Comment by ceritium** [comment]
Could you try to disable the cloudflare email obfuscation?

**Comment by openp2pdesign** [comment]
Yes, with the CloudFlare Email Obfuscation disabled it works.
The problem seems to be with `Labs` that have an **@** in the name... Is there any way to solve this without disabling Email Obfuscation?

![screen shot 2017-01-09 at 14 13 02](https://cloud.githubusercontent.com/assets/1458229/21767721/f1da9ab4-d675-11e6-8386-dc2278783b82.png)

**Comment by ceritium** [comment]
In theory [this](http://roaringapps.com/blog/cloudflare-email-obfuscation/) disable the ofuscation for a block of code, but that component is generated with js and cloudflare still ofuscating the emails.
