### ISSUE TITLE
Show the users who accepted or rejected a Lab

### ISSUE THREAD

**Issue by openp2pdesign** [fablabbcn/fablabs.io#194]
In the Backstage, in the section about `Labs`, we should add information about the users who accepted or rejected or asked for more info for a `Lab`. This should be for superadmins only, at the moment.

![screen shot 2016-12-19 at 17 06 13](https://cloud.githubusercontent.com/assets/1458229/21319434/89eb64ec-c60d-11e6-8505-ad4c09474f30.png)

In some cases as the one above, a `Lab` has been approved but referees seems to be still Pending... there should be more information for superadmins to understand who approved whom, and if it everything is visualized well and there are no bugs here.

**Comment by openp2pdesign** [comment]
... for superadmins and for `Referee Labs`, regarding the `Labs` they approved, see #82

**Comment by vierarb** [comment]
There's no bug here. When a lab is approved but the referees have not taken any action, it means that was the superadmin who did it.

**Comment by openp2pdesign** [comment]
@vierarb then we should add a notification for this in the page, mentioning the specific superadmin that approved it
