### ISSUE TITLE
Improve the e-mail notifications to Referee Labs

### ISSUE THREAD

**Issue by openp2pdesign** [fablabbcn/fablabs.io#195]
The [e-mail notifications](https://github.com/fablabbcn/fablabs/tree/d8f2ab6aa1808288735d25f92a7fe6864c4af511/app/views/referee_mailer) to `Referee Labs` should be improved, at least in this way:

- Add not just the `Lab` creator name, but all the `Lab` employees
- Add more text explaining what the `Referee Lab` is supposed to do
- Add a link to online documentation about the approval process (to be done)
- Add a link to the GitHub repo, if they need to open any issue
- Add a link to the `Discuss` section, if there's something to be discussed about the `Lab` to be approved
- Add greetings at the end of the e-mail

**Comment by openp2pdesign** [comment]
@aldo23 you're one of the users who pointed this out, do you have any suggestion?

**Comment by Aldo23** [comment]
Hey Massi,

maybe we can include in the general email a link to an handbook/instructions to evaluate labs?
Do we have one? I didn't search for it but if there is would be even easier to directly add it to the general email.

Best
Aldo

**Comment by Madouc** [comment]
please also allow a lab to withdraw from the referee process without approving or disapproving.

**Comment by bnore** [comment]
- Create alerts to Referees after requesting more_info from the approval process
- Alert Referees once the lab has updated the information so that they can continue the process
