### ISSUE TITLE
Bug with Supernodes

### ISSUE THREAD

**Issue by openp2pdesign** [fablabbcn/fablabs.io#340]
When [adding a new lab](https://www.fablabs.io/labs/new), any user can choose the `Supernode` category for it, but this is something than only a _superadmin_ should be able to do (the same thing applies then to the Lab edit page in the Backstage):

![screen shot 2017-05-18 at 11 32 44](https://cloud.githubusercontent.com/assets/1458229/26195974/bd851854-3bbd-11e7-85ef-627407b74959.png)

Furthermore, the [Backstage](https://www.fablabs.io/backstage) should have a checkbox for searching all `Supernodes` as it is possible now for `Referees`:

![screen shot 2017-05-18 at 11 34 16](https://cloud.githubusercontent.com/assets/1458229/26196072/0c083a74-3bbe-11e7-814e-83c5023f65b9.png)

**Comment by fibasile** [comment]
Outdated by #362
