### ISSUE TITLE
missing css libraries

### ISSUE THREAD

**Issue by Lyla-Fischer** [fablabbcn/fablabs.io#351]
Context: I'm currently trying to get this repo set up, and I'm logging issues for anything that I find. I'll be making guesses for myself to get through this, but I thought that you might like a record of the process in case you wanted to make it smoother for the next round of people who are trying this. 

Issue: There seems to be a large number of vender css files missing, including select2 and bootstrap. I'm not sure what caused this, but maybe it is a good idea to get that stuff under version control? I can add it myself, but it seems strange to have it missing, so I thought that I would file the issue.

**Comment by Lyla-Fischer** [comment]
(changed the title because I had drafted a different issue and got it figured out. I changed the body of this issue without changing the title after doing that. )

**Comment by viktorsmari** [comment]
Hi @Lyla-Fischer 

There is good work on this pull request: https://github.com/fablabbcn/fablabs/pull/342

It updates gems and adds a README (very much needed) but the tests are failing, which is the reason it is not merged yet. If you have experience with testing / Travis you might be able to fix this pull request, and if you get the tests to pass I would gladly merge it!

Here is the history of our Travis tests build status:
https://travis-ci.org/fablabbcn/fablabs/pull_requests

**Comment by openp2pdesign** [comment]
These libraries are installed with Bower since January 2017 (@6506ecdd522b9ad1a7bda5e6d228242835058844), see [bower.json](https://github.com/fablabbcn/fablabs/blob/master/bower.json).

@Lyla-Fischer have you tried bower? Are there any specific issues with it?

**Comment by Lyla-Fischer** [comment]
It seems like there might be something on the machines y'all are using that picks up these libraries from node.js or something?

**Comment by Lyla-Fischer** [comment]
Nope - I was using node.js. I'll switch over to bower and start over using the pull request from dangerousbeans. See if I can get the tests to pass....

**Comment by Lyla-Fischer** [comment]
I've got a version working, and I'm currently trying to figure out how to run tests. If y'all are reading and would be willing to just tell me, I would appreciate it. Otherwise, I'll keep digging.

**Comment by Lyla-Fischer** [comment]
Progress so far: https://github.com/fablabbcn/fablabs/pull/352
Note that I commented out the discussion forum. I'm not sure what y'all are using for the discussion forum in production, but I didn't really have a method of figuring it out from the repo, and I figured it was an unnecessary dependency anyway, for the short term at least.

**Comment by viktorsmari** [comment]
Run test by issuing `bundle exec rake` in the terminal, in the project folder.

**Comment by viktorsmari** [comment]
In @dangerousebeans last comment, he said he got the project to only 7 failed tests.

**Comment by viktorsmari** [comment]
You should check out his PR - so we wont do the same things 2x
https://github.com/fablabbcn/fablabs/pull/342/files#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by Lyla-Fischer** [comment]
Integration environment tests seem to be passing, for what it's worth.

**Comment by Lyla-Fischer** [comment]
The readme in https://github.com/fablabbcn/fablabs/pull/342 might be more comprehensive. I had to start over a couple of times in order to get this to work, and I lost some of my more detailed notes on what I did. I included the references to things that I previously did not know existed, but I don't have a step-by-step that @dangerousbeans successfully recorded.

**Comment by Lyla-Fischer** [comment]
Updated the README with figaro stuff so that local tests pass.

**Comment by openp2pdesign** [comment]
This should be fixed with #407
