### ISSUE TITLE
Footer image isn't rendering

### ISSUE THREAD

**Issue by Lyla-Fischer** [fablabbcn/fablabs.io#353]
I'm getting an error message from the image_tag in rails

ERROR bad URI `/assets/logos/eu_flag_creative_europe_co_funded_pos_[rgb]_left_300.jpg'

The logo itself is located in assets/images, but that isn't what the image_tag is trying to get at. I'm still quite new to rails, so I don't really know how to start debugging this. (image_tag is magic that I can't decipher at the moment).

**Comment by openp2pdesign** [comment]
Might it be with the new Dockerization? On production we are not using Docker yet and it works well
