### ISSUE TITLE
"Who is fablabs.io for?" section of homepage isn't rendering

### ISSUE THREAD

**Issue by Lyla-Fischer** [fablabbcn/fablabs.io#354]
Just checking out stuff, and it looks like there is a section of the homepage that is also broken on fablabs production. Specifically "Who is fablabs.io for?" doesn't seem to have anything but the sign-up button, but the code looks like it is trying to be similar to the rest of the embedded FAQ. Submitting an issue in case you wanted to look at it.

**Comment by Lyla-Fischer** [comment]
Also, the "Fab Foundation" link also seems to be broken. It seems to be trying to redirect within the same domain rather than going to a new domain. Again, I'm not sure how to fix it, because I am such a Rails n00b, but I thought that I would record the brokenness for you.

**Comment by openp2pdesign** [comment]
@Lyla-Fischer yes, we are aware of this, some details were lost while moving the front-end from Foundation to Bootstrap, and generally Fablabs.io should have a new Visual Identity and UX, we started working on it months ago but it's not online or in the repo yet, but there will be more updates soon. Thanks for reporting :-)
