### ISSUE TITLE
need_more_info status cannot be changed by Referees

### ISSUE THREAD

**Issue by openp2pdesign** [fablabbcn/fablabs.io#357]
When a `Referee Lab` ask a new `Lab` to provide more info (_need_more_info_ status), then the `Referee Labs` cannot accept it later, only _superadmins_ can... _Referee Labs_ should be able to change this status.

**Comment by Madouc** [comment]
Can this be bumped to High Priority?
i also have this issue for  https://www.fablabs.io/backstage/labs/fablabraseko (id 1473)
this lab wants to open next month is would like to be on the map for the opening.
Fablab Reykjavik already approved, and now Frosti (fablab vestmannaeyar) is trying to approve

**Comment by vierarb** [comment]
@openp2pdesign I noticed there's a button to request admin approval. Should I keep the button or get rid of if?

**Comment by openp2pdesign** [comment]
@vierarb Let's keep it, we'll probably have to change the UX a bit but to improve it, but for the moment let's keep it the way it is.

**Comment by TheBeachLab** [comment]
Hi there. Did the issue close because it was solved? I have a lab who I requested more info. They provided, but now I cannot change their status.
