### ISSUE TITLE
Delete supernodes kind of Labs

### ISSUE THREAD

**Issue by openp2pdesign** [fablabbcn/fablabs.io#362]
After the recent changes in the Fab Academy after FAB13, we don't need to have _supernodes_ `Labs` any longer, so we should delete this information (_supernodes_ do not exist any longer and we don't need this information):

https://github.com/fablabbcn/fablabs/blob/4b2151ef297354d5b105d63c3df56c8f58f1eaf8/app/models/lab.rb#L83

This would also solve #340

**Comment by wendwarge** [comment]
Awesome, there are supernodes liberally sprinkled everywhere (#340) and you're absolutely right, the word 'supernode' has been retired.

**Comment by Lyla-Fischer** [comment]
Is this something that can just be pulled out, or does it have any extra functionality around it? I see that most places, it is just an option that is almost a tag, which means that it should be decently easy to remove. 

I also see that it is included in some of the apiary stuff. I don't know much about apiary - can we just remove it from there too?
