### ISSUE TITLE
Show which Labs are now closed

### ISSUE THREAD

**Issue by openp2pdesign** [fablabbcn/fablabs.io#375]
Once we will have complete (or almost complete) data about when Labs where created or closed from #108, we should clearly make a list of closed Labs and visualize them in a different way in their own page. This is important in order to keep an history of the network.

**Comment by LinusEkenstam** [comment]
@openp2pdesign - regarding this ticket, do we have the correct backend support for this so we can add the "CLOSED TAG"  in the lab list view. Please ping @fbaiodias about this if we have the support for it.
