### ISSUE TITLE
Rename the repo Fablabs.io

### ISSUE THREAD

**Issue by openp2pdesign** [fablabbcn/fablabs.io#383]
In order to make things clearer for everybody and especially the whole Fab Lab network, we should rename this repo to **Fablabs.io**. There are way too many repositories with similar "Fab Lab" names. Usually it's not a big deal on GitHub, and now that we are changing the infrastructure & dockerization, it should be easy to do and fix any conflicts.

**Comment by viktorsmari** [comment]
- [ ] Gitmodules
- [ ] Capistrano deploy tasks

**Comment by openp2pdesign** [comment]
maybe we ca skip Capistrano for this, and just fix it for the dockerization?
