### ISSUE TITLE
Fablab is unable to add location information when applying for a new laboratory

### ISSUE THREAD

**Issue by Jackliu888** [fablabbcn/fablabs.io#390]
When we apply for a new laboratory, the laboratory map is not shown in the application list. 
I wonder if this is a map interface in addition to the problem?
What can we do to solve this problem？

**Comment by openp2pdesign** [comment]
Have you find a valid address in Step 1? 

![screen shot 2018-03-02 at 13 52 05](https://user-images.githubusercontent.com/1458229/36899798-f298f0c4-1e20-11e8-94f7-aafeb5022922.png)

**Comment by Jackliu888** [comment]
I can't show the address of the map here.

![image](https://user-images.githubusercontent.com/34561840/37009226-feb91502-2120-11e8-96d4-612dc35785ee.png)

**Comment by openp2pdesign** [comment]
I guess the problem is: your address has too many details for the Google Place Autocomplete.

With just this it works: 53 Deng Shi Kou Da Jie, DongDan, Dongcheng Qu, Beijing Shi, Cina, 100010

![screen shot 2018-03-06 at 16 21 22](https://user-images.githubusercontent.com/1458229/37040566-78e880cc-215a-11e8-8ba5-a1986aa4be11.png)


You can add the other details in Step 2

**Comment by Jackliu888** [comment]
Thank you for your help.
I've tried a variety of fields and keywords, but the map has never been shown.Is it the problem of our firewall in China?Some reasons cause the map interface not to be displayed properly。
Is it possible to add a map after the laboratory certification is passed? Our laboratory has already submitted authentication, and I want to know how to make our Fab Lab C+ normal on the web site?

![image](https://user-images.githubusercontent.com/34561840/37068664-c5f562be-21ea-11e8-84de-67bc94445752.png)

**Comment by openp2pdesign** [comment]
Ah yes, this might be the issue, the firewall! 

https://productforums.google.com/forum/#!topic/maps/7ICn0NKWnPw
https://stackoverflow.com/questions/46662233/how-to-use-google-places-api-web-service-in-china

We'll probably have to look for another service, or that's something us admins have to do manually then..

**Comment by openp2pdesign** [comment]
I'll open a more specific issue for this

**Comment by openp2pdesign** [comment]
@Jackliu888 can you try if it works with OpenStreetMap there? 

https://nominatim.openstreetmap.org/search.php?q=+Deng+Shi+Kou+Da+Jie%2C+Beijing+China&polygon_geojson=1&viewbox=

**Comment by Jackliu888** [comment]
Thank you very much.
I can access your map link.That can really be a problem with the map data interface.

**Comment by Jackliu888** [comment]
Our laboratory has already submitted authentication, and I want to know how to make our Fab Lab C+ normal on the web site?
We contacted three referee laboratories, one of which didn't know how to operate the feedback, and second of them could not find the location of the certification reminders, and the third feedback kept the communication with other laboratories.

**Comment by openp2pdesign** [comment]
@Jackliu888 one more question: could you try with this as well? https://www.mapbox.com/help/how-geocoding-works/

I'll then reply to your e-mail about your application

**Comment by Jackliu888** [comment]
Thank you for help.
Most of the time can be accessed normally, and when the speed of the network is slow, it can't be loaded.
![image](https://user-images.githubusercontent.com/34561840/37192762-2950d132-23a2-11e8-860f-629e10ce3388.png)
One more thing，Will the Fablab website edit the Chinese version? Now it's a pure English version, it's difficult for some Chinese users to read. At present, there are no referee laboratories in the mainland of China. What are the conditions for the laboratory to be judged as a referee's laboratory?

**Comment by openp2pdesign** [comment]
You can add a Chinese translation here! Do a pull request and we'll add it: https://github.com/fablabbcn/fablabs.io/tree/master/config/locales

**Comment by openp2pdesign** [comment]
Referees: we are working on it, more updates soon

**Comment by Jackliu888** [comment]
Thank you so much.
What I need to do is to translate the content of the page into Chinese and submit it to the database？

**Comment by openp2pdesign** [comment]
1. Fork the repo
2. Copy [en.yml](https://github.com/fablabbcn/fablabs.io/blob/master/config/locales/en.yml) to zh.yml and edit it
3. Create a Pull Request with your version
4. We'll add it
