### ISSUE TITLE
A Discourse thread is not created when more than 2 links are in the description

### ISSUE THREAD

**Issue by openp2pdesign** [fablabbcn/fablabs.io#391]
There's a weird message error in a `Lab`, the Discourse thread is not automatically generated because:

`{"action":"create_post","errors":["Sorry, new users can only put 2 links in a post."]}`

The description of the `Lab` says:

> :bulb: DAMA Space :bulb: ---------- Our FabLab "DamA Space" born from a partnership with [3DiTALY](http://www.3ditaly.it/) and [DAMA – Digital Arts & Manufacturing Academy](http://www.dama.academy), in Milano and is able to manage educational activities and support to craftman community. ---------- :tools: We have a lot of technologies: 3d printers, robotic arms, laser cutters, milling machines, software CAD locations, vinil plotters. :calendar_spiral: We are open every days to spread the opportunities and the potentials of digital fabrication. :electric_plug: We are connected with Milano's Makerspaces Network. :muscle: The founders of our fablab are a perfect mix of knowlodges: physicits, architects, designers, jueles designer. ---------- :arrow_right: http://www.dama.academy/dama-makerspace-milano/

It is a problem for Discourse, but most likely also in other parts of the platform...

**Comment by openp2pdesign** [comment]
Related to #376

**Comment by vierarb** [comment]
This can be configured on Discuss directly. I've set it to 5, so no code required.
