### ISSUE TITLE
Users should not be searchable

### ISSUE THREAD

**Issue by openp2pdesign** [fablabbcn/fablabs.io#401]
Users can be searched, this should be changed: users should not apper in research results

**Comment by openp2pdesign** [comment]
Remove:

- https://github.com/fablabbcn/fablabs.io/blob/d8f2ab6aa1808288735d25f92a7fe6864c4af511/app/controllers/search_controller.rb#L11
- https://github.com/fablabbcn/fablabs.io/blob/d8f2ab6aa1808288735d25f92a7fe6864c4af511/app/controllers/search_controller.rb#L13

**Comment by openp2pdesign** [comment]
Remove also:
- https://github.com/fablabbcn/fablabs.io/blob/d8f2ab6aa1808288735d25f92a7fe6864c4af511/app/controllers/concerns/users_operations.rb

**Comment by openp2pdesign** [comment]
Or: users should be searchable and accessible only by logged in users

**Comment by viktorsmari** [comment]
Why should users not be searchable?
Do you agree with this @bnore?

I think it is very useful to be able to search for a user.
You can see them anyway under each labs employee section.
