### ISSUE TITLE
Replace bower with npm

### ISSUE THREAD

**Issue by fibasile** [fablabbcn/fablabs.io#407]
Bower is deprecated, should be replaced by yarn or npm

According to this

https://bower.io/blog/2017/how-to-migrate-away-from-bower/

it should be (almost) painless

**Comment by viktorsmari** [comment]
@fibasile if you are working on this, I already did some work on a PR https://github.com/fablabbcn/fablabs.io/pull/368/files if you want to see what I did or use some of it.

**Comment by viktorsmari** [comment]
Done
