### ISSUE TITLE
Labs Embed Map doesn't work on the test version

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/fablabs.io#434]
### Expected behaviour
https://www.fablabs.io/labs/embed
https://www.fablabs.io/labs/map

### Actual behaviour
https://test.fablabs.io/labs/embed
https://test.fablabs.io/labs/map

### How to reproduce?
Open the URL

**Comment by openp2pdesign** [comment]
Duplicated / related to #422

**Comment by openp2pdesign** [comment]
<img width="397" alt="screen shot 2018-09-13 at 16 18 24" src="https://user-images.githubusercontent.com/1458229/45494147-be327c80-b770-11e8-974f-21a0ed189437.png">

**Comment by viktorsmari** [comment]
It would also be nice to make sure our tests catch if this fails or not, for the future.

**Comment by pral2a** [comment]
@fibasile I guess what @fbaiodias found is due to the last changes on the API? 

We should keep the legacy endpoint to support embedded maps so if we want to keep the new format (without `labs`) we should use a different end-point. 

I guess the best will be to use the api.fablabs.io for that end-point as it is use by other external map applications and also add versioning on the API paths to avoid issues

**Comment by viktorsmari** [comment]
Fixed
