### ISSUE TITLE
Sign in and sign out buttons position on header bar

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/fablabs.io#435]
![screen shot 2018-09-13 at 16 18 51](https://user-images.githubusercontent.com/74249/45494266-f639bf80-b770-11e8-9952-96ca202f852f.png)

**Comment by pral2a** [comment]
@viktorsmari Is this deployed? I can still see the problem in my browser

Thanks!

**Comment by viktorsmari** [comment]
I have deployed to both https://staging.fablabs.io/ and https://test.fablabs.io/
@fbaiodias - is the issue still there?
