### ISSUE TITLE
Link to Discuss page is broken

### ISSUE THREAD

**Issue by openp2pdesign** [fablabbcn/fablabs.io#436]
The link to Discourse should be changed from 

https://github.com/fablabbcn/fablabs.io/blob/master/app/views/application/_header.html.haml#L36

to:

https://test.fablabs.io/discuss

**Comment by LinusEkenstam** [comment]
@openp2pdesign - are you sure you want a hard-coded link to the test subdomain in the platform?

**Comment by viktorsmari** [comment]
We don't, and won't have a test discourse instance.
