### ISSUE TITLE
FabLab Leon is on the list but does not appear in the map

### ISSUE THREAD

**Issue by nunuromi** [fablabbcn/fablabs.io#449]
I don't know if it happens with other labs, but the localization in the map of FabLab Leon seems to be missed
<img width="599" alt="captura de pantalla 2018-10-26 a las 0 15 26" src="https://user-images.githubusercontent.com/6595077/47533633-c5db5a00-d8b4-11e8-8013-146b6cd29a5c.png">

**Comment by viktorsmari** [comment]
I just seems like this lab has a `kind:null`, if you compare these 2
```json
{
id: 893,
name: "FABLAB KERALA - Kochi",
slug: "fablabcochin",
latitude: 10.0554474,
longitude: 76.3553466,
kind: "fab_lab"
},
{
id: 72,
name: "Fab Lab Leon",
slug: "fablableon",
latitude: 42.6110431,
longitude: -5.59782100000007,
kind: null
}, 
```

Is there a missing setting for this lab?

**Comment by viktorsmari** [comment]
Here is the raw data: https://fablabs.io/labs/mapdata.json
And those 2 are the same:
```json
{
id: 1202,
name: "FabLab Toledo",
slug: "Toledo",
latitude: 39.9833364,
longitude: -4.28114270000003,
kind: null
},
{
id: 477,
name: "Fab Lab Talavera",
slug: "fablabtalavera",
latitude: 39.958033,
longitude: -4.83221789999993,
kind: null
},
```

**Comment by viktorsmari** [comment]
All the Fablabs are now using the same icon, so Leon should be visible.
Thank you for reporting the bug @nunuromi !
