### ISSUE TITLE
136 labs have a `kind: null`

### ISSUE THREAD

**Issue by viktorsmari** [fablabbcn/fablabs.io#450]
According to this we have 136 labs with `kind: null`
https://fablabs.io/labs/mapdata.json

1. Should this be possible? 
2. Should we manually change it or can the user change it? @openp2pdesign 
3. Should all the labs have the same icon on the map?

Now if a lab has a `kind: null` it does not have the Fablab logo on the map, it only appears as 'a dot'

See #449 for example

**Comment by fibasile** [comment]
Kind should have a default value of "fablab"
