### ISSUE TITLE
Approve labs direct link not working

### ISSUE THREAD

**Issue by TheBeachLab** [fablabbcn/fablabs.io#460]
**Describe the bug**
In the past when you go visit https://www.fablabs.io/backstage/to_approve_labs you go to login page then you enter the backstage. Now it gives you an error and ask the admin to check logs 

**To Reproduce**
1. Logout
2. go to https://www.fablabs.io/backstage/to_approve_labs

**Expected behavior**
A login page appears, then the backstage

**Comment by viktorsmari** [comment]
Thank you for reporting @TheBeachLab 
This will first be deployed to https://staging.fablabs.io/backstage/to_approve_labs and to production soon
