### ISSUE TITLE
Font loading errors - no route matches

### ISSUE THREAD

**Issue by viktorsmari** [fablabbcn/fablabs.io#461]
ActionController::RoutingError (No route matches [GET] "/assets/circle-logo-e1bbc5912a6cd2dd5ac0e1a4f6a535e3.png"):
ActionController::RoutingError: No route matches [GET] "/fonts/fontawesome-webfont.woff2"
ActionController::RoutingError (No route matches [GET] "/fonts/fontawesome-webfont.ttf"):
ActionController::RoutingError (No route matches [GET] "/v0/labs.json"):

**Comment by fibasile** [comment]
I think this can be closed as is outdated.
