### ISSUE TITLE
Discourse embed broken in lab detail page

### ISSUE THREAD

**Issue by fibasile** [fablabbcn/fablabs.io#466]
**Describe the bug**
The lab page fail to show the Discourse embed 

**To Reproduce**
1. Visit a lab page
2. check the bottom of the page for the error

**Expected behavior**
The embed should show the thread or a link to the thread

**Screenshots**
![image](https://user-images.githubusercontent.com/32947/53088083-04062480-3509-11e9-9ba2-154e847d6b42.png)

**Comment by viktorsmari** [comment]
The domain was missing in the embedding settings:
https://discuss.fablabs.io/admin/customize/embedding

Fixed.
