### ISSUE TITLE
Wrong placement of pagination in Organizations list

### ISSUE THREAD

**Issue by fibasile** [fablabbcn/fablabs.io#468]
**Describe the bug**
The pagination links are placed on the right of the last card in desktop view and on the top right of the screen in mobile view

**To Reproduce**
1. Visit the organizations page on desktop and mobile

**Expected behavior**
Pagination links should show up always at the bottom of the list, after the items.

**Screenshots**
Desktop
![image](https://user-images.githubusercontent.com/32947/53088429-f8ffc400-3509-11e9-934f-5c63d28bed24.png)

Tablet
![image](https://user-images.githubusercontent.com/32947/53088485-29476280-350a-11e9-80df-de4913f594d0.png)

**Comment by viktorsmari** [comment]
Fixed after Bootstrap 4 update
