### ISSUE TITLE
Could we add a category of Humanitarian? 

### ISSUE THREAD

**Issue by Ceciwantstolearn** [fablabbcn/fablabs.io#515]
**Is your feature request related to a problem? Please describe.**
Cecilia here from Field Ready, we wanted to ask if Fablabs.io could add a category of Humanitarian on the forum, as we want to contribute lots of contents and encourage discussion and share best practices and knowledge. However, at the moment, there is no relevant category where we could post these content. 

**Describe the solution you'd like**
Add a category 'Humanitarian' into the Fablabs.io website and forum. 

**Describe alternatives you've considered**
Maybe there is another way to categorise these contents and discussion? A tag?

**Comment by viktorsmari** [comment]
Hi @Ceciwantstolearn, there is now a Humanitarian tag on the forum: 
http://discuss.fablabs.io/c/humanitarian
