### ISSUE TITLE
No such service: web

### ISSUE THREAD

**Issue by sbonaime** [fablabbcn/fablabs.io#525]
**Describe the bug**
I have a problem with docker-compose :
```
docker-compose up web app
ERROR: No such service: web
```

**Desktop (please complete the following information):**
commit 6362d24ff2505f8017f9180d198c0a3c88fb92f
debian 9.11

**Comment by viktorsmari** [comment]
Thank you for reporting @sbonaime !

This is wrong, and we will update the README.

`web` container is not used in this project!
