### ISSUE TITLE
Pagination is broken for list of machines; shows the same page of results for several minutes

### ISSUE THREAD

**Issue by stuikomma** [fablabbcn/fablabs.io#532]
**Describe the bug**
When you go to https://www.fablabs.io/machines, you will see a list of machines. When you go to a different results page, you will see the _same_ list again. Even across hard refreshes and different browsers.

When I went back a few minutes later, I would see a _different_ list, but again I couldn't use the pagination.

**To Reproduce**
1. Go to https://www.fablabs.io/machines
2. Click page 2 at the bottom of the page. This will navigate you to https://www.fablabs.io/machines?page=2 
2. See the same results again

**Expected behavior**
At 3. I expected the second page of machines to be shown instead of the first.

**Screenshots**
![image](https://user-images.githubusercontent.com/2040603/73138564-3a76e880-4064-11ea-94a0-9f81be399348.png)
![image](https://user-images.githubusercontent.com/2040603/73138561-3054ea00-4064-11ea-9483-d9307fbdf4f0.png) Note the different URL in this screenshot.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser 
  - Chrome 79.0.3945.130
  - Firefox 72.0.2 (64-bit)
  - curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL

**Additional context**
Looks like some form of caching problem to me. And believe me it feels really weird, that't why I even tried curl and even tethering from my phone to make sure it's not a network problem :)

**Comment by viktorsmari** [comment]
Should be fixed in e4383ce32ded3db3568c2463e29170d7d105ac3c

Caching was conflicting with pagination.
