### ISSUE TITLE
login to https://discuss.fablabs.io/ does not work

### ISSUE THREAD

**Issue by ARKopp** [fablabbcn/fablabs.io#537]
**Describe the bug**
login does nor work with fablabs.io account it says SSO error

**To Reproduce**
Just try to login

**Expected behavior**
normally i would get logged in 

**Screenshots**
![Screenshot 2020-03-05 11 57 14](https://user-images.githubusercontent.com/4289157/75975690-44003580-5ed9-11ea-9580-ae907e0a31b4.png)

**Comment by viktorsmari** [comment]
Confirmed. 

Relevant log:

>Started GET "/discourse/sso?sso=XXX
Processing by DiscourseController#sso as HTML
  Parameters: {"sso"=>"xxx=", "sig"=>"zzz"}
uninitialized constant DiscourseController::SingleSignOn
Did you mean?  Singleton
["/fablabs/app/controllers/discourse_controller.rb:9:in `sso'",

**Comment by viktorsmari** [comment]
Fixed in be0ca23ac85602360780ea8504620187f9919295

**Comment by ARKopp** [comment]
thanks!
