### ISSUE TITLE
Lab edit: Cannot see already selected machines. Cannot remove machines

### ISSUE THREAD

**Issue by viktorsmari** [fablabbcn/fablabs.io#542]
## Problem
Cannot remove machines in a Lab
Cannot see which Machines have been added

## Reproduce
1. Edit a lab.
2. Add machines and update.

You should be able to see which machines you added.

Instead the list is empty, however the already selected machines are not on the list.

How can you remove machines?

![2020-04-07_13-10-13](https://user-images.githubusercontent.com/1689020/78663054-c82b4b80-78d1-11ea-86ba-e8ffb0e97196.png)

It could be a combination of:
https://stackoverflow.com/questions/2196382/rails-select-tag-with-multiple-values-pre-selected/2196522

We can disable select2 while debugging, because it is applied to ALL selects

**Comment by bnore** [comment]
People tend to add machine in this space: 
<img width="749" alt="Screen Shot 2020-04-15 at 1 01 19 PM" src="https://user-images.githubusercontent.com/24419466/79371012-45317300-7f19-11ea-84d8-ff27418036cb.png">

We need to figure out a way in which under this section: 

<img width="806" alt="Screen Shot 2020-04-15 at 1 03 07 PM" src="https://user-images.githubusercontent.com/24419466/79371131-79a52f00-7f19-11ea-8b8d-b656f7f85a0c.png">
 
To have conditional dropdown boxed based on what they choose where they can select brand and model of their machine, that is pulled from the machine section in FabLabs.io

**Comment by tuengominh** [comment]
Hi @bnore 

I will create another issue for this!

Thanks
