### ISSUE TITLE
need help on registering new Lab

### ISSUE THREAD

**Issue by makersnr** [fablabbcn/fablabs.io#554]
**Describe the bug**
Hi, I wanted to add the Lab on the Fablabs.io website and there seems to have an issue. 
there is this popup where it says " we're sorry, but something went wrong - if you are the application owner check the logs for more information"  
I don't quite understand the problem and need a bit of support on this issue. 
hope to hear from you 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/67886859/86557283-ad2fac80-bf90-11ea-9c3a-375f9d74fc27.png)

**Desktop (please complete the following information):**
chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by viktorsmari** [comment]
Can you try again and see if the error is still there?

**Comment by makersnr** [comment]
Yes I've tried multiple times and it's still an issue.

2020년 7월 6일 (월) 오후 8:53, Viktor Smári <notifications@github.com>님이 작성:

**Comment by viktorsmari** [comment]
Thank you for reporting and testing, we think we have fixed the bug now!
Can you try again please? :smile_cat:

**Comment by makersnr** [comment]
Yes! it worked and have received an email about successful submissions. .
thanks!

2020년 7월 7일 (화) 오후 4:15, Viktor Smári <notifications@github.com>님이 작성:
