### ISSUE TITLE
Orgs give you an error

### ISSUE THREAD

**Issue by ARKopp** [fablabbcn/fablabs.io#557]
![Screenshot 2020-07-27 13 19 40](https://user-images.githubusercontent.com/4289157/88536290-e1384380-d00b-11ea-9d40-d1bbc4f452a8.png)
**Describe the bug**
clicking on any orgs gibe your an error

https://fablabs.io/organizations/fab-antipodes

**To Reproduce**
1. Go to "orgs"
2. Click on andy organisation

**Comment by viktorsmari** [comment]
This was a problem with Redis on the server.
It did not have a memory limit and started using all the resources.

We hope the issue has been fixed!
