### ISSUE TITLE
discourse login error

### ISSUE THREAD

**Issue by HenkATwaag** [fablabbcn/fablabs.io#559]
I can login to fablabs.io. But when i go to 'discuss', a new tab is being opened, with discourse. When i press the login button i'm redirected to a page that says "There is a problem with your account. Please contact the site's administrator."

Not only me: also Pradnya07 and @nunuromi  have the same problem.

**Comment by pietervanderhijden** [comment]
Me too!

**Comment by viktorsmari** [comment]
I have the same issue. 
I can log in to GitLab (fabcloud) with fablabs.io and other services, so the issue is on the Discourse server.
I updated Discourse to the latest version and restarted the server, but the issue is still there.

**Comment by viktorsmari** [comment]
Can you try again?
Some IP's were blocked, I don't know why. I was able to log in again.

**Comment by HenkATwaag** [comment]
i can login again :) Goto fablabs.io / login / goto discuss / have to click login / and then i'm logged in without need to login to fablabs.io again.

So it looks like the problem was the connection between fablabs.io and discourse...

**Comment by pietervanderhijden** [comment]
I also can login again! Thank you, @viktorsmari
