### ISSUE TITLE
Remove Empolyees

### ISSUE THREAD

**Issue by ZapLabSuriname** [fablabbcn/fablabs.io#576]
**I am trying to remove an employee from the overview by clicking the REMOVE button. 
I am then redirected to a page that does not exist. _The page you were looking for doesn't excist. You may have mistyped the address or the page may have moved._** 

1. Go to https://fablabs.io/labs/ZapLab
2. Click on the button: Manage lab -> edit employee list
3. All the Employees appear. 
4. Click on the REMOVE button near the Employee you want to remove
5. a new window appear https://fablabs.io/employees/5656 with the message: _The page you were looking for doesn't excist. You may have mistyped the address or the page may have moved._ 

I expected that there would be a question (do you really want to delete it) where I can click accept. 

![fablabs IO remove 2](https://user-images.githubusercontent.com/80415949/110671313-1ebd9b80-81ad-11eb-8750-ddc5231d278b.jpg)

**Desktop (please complete the following information):**
 - Windows 10
 - Browser Firefox

**Comment by viktorsmari** [comment]
Thank for this detailed report!
I found out that some javascript was breaking on the site, resulting in the 'Are you sure' popup to break, which also broke the delete method.
I activated the `rails-ujs` library and the issue **should** now be fixed!
