### ISSUE TITLE
inventory link broken

### ISSUE THREAD

**Issue by niccokunzmann** [fablabbcn/fablabs.io#613]
**Describe the bug**

**To Reproduce**
1. Go to https://www.fablabs.io/labs/new
2. Click on [official Fab Lab inventory](http://fab.cba.mit.edu/about/fab/inv.html).
4. See error 404

**Expected behavior**

I would like to see the inventory.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MacTwister** [comment]
Thank you @niccokunzmann for reporting

Updated the links on the create lab form with 5e8cd907
