### ISSUE TITLE
Search engine weird behavior

### ISSUE THREAD

**Issue by TheBeachLab** [fablabbcn/fablabs.io#88]
The search engine has a weird behavior when looking for lab names.

Example 1: The Beach Lab
-  the beach lab <---- not found
- beach lab <----- not found
- beach <----- found

So at the beginning I thought that it does not work with multiple words, but this other case makes me thing there is something wrong in the search engine

Example 2: 1Bacteria Fab Lab
- 1bacteria <---- not found
- 1Bacteria <---- not found

**Comment by hiromipaw** [comment]
Hi,
The search engine is being redefined. At the moment it searches for the slug only and ignores spaces. 
In the examples you make you do not find 1bacteria because the slug is baterialab.

**Comment by TheBeachLab** [comment]
Thanks, so for example the slug for The Beach Lab is `thebeachlab`. If i search for `the beach lab`, or `beach lab` if it ignores spaces, shoudn't it find it?

**Comment by hiromipaw** [comment]
When I said it ignores spaces I meant it doesn't look for multiple words, but treat everything as a string it should match. If fablabs.io would accept slugs of the form "the beach lab" (spaces includes) it would find it. In this case it works only if you write thebeachlab or part of it (*it* being the lab slug).

**Comment by fibasile** [comment]
Addressing this in PR #481
