### ISSUE TITLE
Problem with the adding a referee

### ISSUE THREAD

**Issue by openp2pdesign** [fablabbcn/fablabs.io#92]
Error found by a lab while adding a supernode:

![screen shot 2016-10-27 at 16 39 28](https://cloud.githubusercontent.com/assets/1458229/19771677/052aeda4-9c64-11e6-8cf4-1bff3b5f79fc.png)

**Comment by hiromipaw** [comment]
This is not a bug. You always have to select 3 referees. The only thing wrong is the error message.

**Comment by openp2pdesign** [comment]
Thanks, I now labeled this as an enhancement, it is more a UX issue (but is it this part of the frontend or of the backend?)

**Comment by hiromipaw** [comment]
Uhm, well error message will be both frontend (how to display it) and backend/api (how to return it and what codes). Also we might decide that if you select a parent supernode you do not need the standard approval process. But not sure about this.
